version: "3"
services:
    # frontend:
    #     build:
    #         context: ./frontend
    #         dockerfile: Dockerfile
    #     image: svelte-settlements
    #     container_name: settlemenets-svelte
    #     command: yarn dev --host
    #     ports:
    #         - "5001:5713"
    #        # - "35729:35729"
    #     volumes:
    #         - ./frontend:/app
    #     depends_on:
    #         - api
    api:
        build: 
            context: ./thesettlements-api
            dockerfile: Dockerfile
        image: thesettlements-backend
        container_name: The-Settlements-API
        command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
        ports:
            - "8001:80"
        volumes:
            - ./thesettlements-api/app:/api/app
        depends_on:
            - db
    db:
        image: neo4j:latest
        container_name: The-Settlements-DB
        ports:
            - "7474:7474"
            - "7687:7687"
        env_file: 
            - ./thesettlements-api/.env
        
