version: "3"
services:
    # frontend:
    #     build:
    #         context: ./frontend
    #         dockerfile: Dockerfile
    #     image: svelte-settlements
    #     container_name: settlemenets-svelte
    #     command: yarn dev --host
    #     ports:
    #         - "5001:5713"
    #        # - "35729:35729"
    #     volumes:
    #         - ./frontend:/app
    #     depends_on:
    #         - api
    api:
        build:
            context: ./thesettlements-api
            dockerfile: Dockerfile
        image: thesettlements-backend
        container_name: The-Settlements-API
        command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
        ports:
            - "8001:80"
        volumes:
            - ./thesettlements-api/app:/api/app
        depends_on:
            - db
    db:
        image: edgedb/edgedb
        container_name: The-Settlements-DB
        environment:
            EDGEDB_SERVER_SECURITY: insecure_dev_mode
        volumes:
             - ".thesettlements-api/dbschema:/dbschema"
        ports:
            - "5656:5656"
        env_file:
            - ./thesettlements-api/.env
