version: "3"
services:
    frontend:
        build:
            context: ./frontend
        ports:
            - "3022:3000"
        depends_on:
            - backend
    backend:
        build: 
            context: ./backend
        ports:
            - "8022:80"
        depends_on:
            - db
        environment:
            - NEO4J_BOLT_URL=bolt://neo4j:admin@db:7687
    db:
        image: neo4j
        ports:
            - "7474:7474"
            - "7687:7687"
        environment: 
            - NEO4J_dbms_memory_pagecache_size=512M
            - NEO4J_dbms.memory.heap.initial_size=512M
            - NEO4J_dbms_memory_heap_max__size=512M
            - NEO4J_AUTH=neo4j/admin
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - dbms.connector.bolt.listen_address=:7687
            - dbms.connector.bolt.advertised_address=:7687
